### PR TITLE
Fix Issue #11: Print new incoming message on a newline

### PR DESCRIPTION
**Pull request by vitokhangnguyen**
This PR fixes issue #11. Two major problems it fixes:
* Always print a new message on a new line
* Keep the input line at the bottom of the conversation if that message has not been sent

### CODE REVIEW

**Comment by Haider8** [comment]
@vitokhangnguyen I don't this is working correctly. Please test it locally again

**Comment by vitokhangnguyen** [comment]
Hi @Haider8, can you be more specific on what went wrong? I am testing locally on both Windows and Linux subsystem. It seems to be ok for me.

**Edit:** I am working on merging with the new master. I didn't know the master branch was updated.

**Comment by vitokhangnguyen** [comment]
I have a few things fixes and merge with the current master. It works for me right now in both Windows and Linux subsystem.

**Comment by Shanmugapriya03** [comment]
@vitokhangnguyen I think you didn't get a clear understanding of the issue
Consider there are 2 users and while one user is currently typing the other user sends a message and it gets printed on the same line where the cursor currently is it will be kind of annoying for that other user who is typing.
Can you follow anyone of [this](https://github.com/Haider8/tmessage/issues/11#issuecomment-538861553) implementation to fix this issue?

**Review by Shanmugapriya03 — CHANGES_REQUESTED** [review]
Needs a different implementation to fix this issue!

**Comment by vitokhangnguyen** [comment]
Hi @Shanmugapriya03,
I think I do get the problem and, on my side, I tested that while I was typing but did not send on one console, I opened another console and sent a message. The new message does not appear at the end of the input line anymore. Instead, the input line is moved down one line and leaves the current line for the new incoming message.

Is this not what happens on your side? Please make sure you cloned this branch and did `pip install .` again.

As for the implementation, could you clarify how different my current from your intention?

**Comment by Shanmugapriya03** [comment]
I couldn't see the behaviour you explained above. Will try once again and let you know @vitokhangnguyen by tomorrow

**Comment by vitokhangnguyen** [comment]
Clone and `pip install .` this branch with the changes: https://github.com/vitokhangnguyen/tmessage/tree/issue-11

If the behavior is not as described above, please give me some feedback about how it is and how it is different from the original.

**Comment by Shanmugapriya03** [comment]
@vitokhangnguyen This is the behavior I am getting  
Screenshot 2019-10-16 at 9 59 21 PM

**Comment by vitokhangnguyen** [comment]
I will take a look into that and give some changes/feedback soon.

Thank you for your effort!

**Comment by vitokhangnguyen** [comment]
I did not attempt to improve much but can anyone using a Windows system test this for me? It does work on my Windows system.
I just want to know if the solution does not work at all or it is a system-dependent thing.

**Comment by Haider8** [comment]
@vitokhangnguyen Sorry, I don't have windows. Have you tried checking that when user1 is typing the message and then when another user sends the message it doesn't get printed right next to the message already typed by user1?

**Comment by vitokhangnguyen** [comment]
Hi @Haider8 and @Shanmugapriya03,
Sorry for the quite slow reply. I have been trying to figure out a way to show this.
Yes, the message already typed is not being continued by the received message.
Here is the behaviour I have been having: https://ibb.co/G3MKDhQ

I am pushing a small change, hope that help.

**Comment by Shanmugapriya03** [comment]
Hi, @vitokhangnguyen I don't have a windows machine but this is the behavior I am getting and also authentication is not working.
Screenshot 2019-10-18 at 11 57 03 AM

**Comment by vitokhangnguyen** [comment]
I am guessing so far this is a system-dependent thing. What I am using is the "\r" carriage return character to overwrite the current typing line with the incoming message. Maybe different systems render the "\r" character differently. I will find a way around this.

May I know what is your current system or, specifically, what terminal are you using?

**Comment by vitokhangnguyen** [comment]
However, I have a feeling that you are not having the version of code I am.
If the "\r" is not rendered correctly on different systems, the message you are typing should be re-printed since I have a print statement that does exactly that in `cli.py` (after the print of normal message).
You did `pip install .` again before doing `tmessage --user [user_name]`, right?

**Comment by Haider8** [comment]
> May I know what is your current system or, specifically, what terminal are you using?

I am using `xubuntu 16.04 LTS` and I am using it's default terminal, that is `xfce4-terminal 0.6.3`

**Comment by Shanmugapriya03** [comment]
@vitokhangnguyen  I did `pip install .` and then initiated a chat
But it is showing this error
```
Priya:tmessage shanmugapriyar$ tmessage --user priya
Traceback (most recent call last):
  File "/Users/shanmugapriyar/.pyenv/versions/3.6.0/bin/tmessage", line 5, in <module>
    from tmessage.cli import main
  File "/Users/shanmugapriyar/.pyenv/versions/3.6.0/lib/python3.6/site-packages/tmessage/cli.py", line 9, in <module>
    from tmessage.input import Input  # input.py
  File "/Users/shanmugapriyar/.pyenv/versions/3.6.0/lib/python3.6/site-packages/tmessage/input.py", line 2, in <module>
    from readchar import readkey, key
ModuleNotFoundError: No module named 'readchar'
```

**Comment by Haider8** [comment]
do `pip install readchar`

**Comment by vitokhangnguyen** [comment]
@Shanmugapriya03 Just for sure, do reinstall all package in requirements.txt:
```
pip install -r requirements.txt
```
with the new source code.

**Comment by Shanmugapriya03** [comment]
@vitokhangnguyen This is the behavior I am getting @Haider8 is it working for you?
Screenshot 2019-10-18 at 9 14 09 PM

**Comment by vitokhangnguyen** [comment]
@Shanmugapriya03 Thank you for testing out.
There is something strange here that when you type your password, it should not appear on the terminal sine there is issue #44 that fixed this. This might suggest that you are somehow still on an old version of the code.

**Comment by Shanmugapriya03** [comment]
@vitokhangnguyen  Can you see the image above? I am in your branch. If it is old version of code then your branch has an old version

**Comment by vitokhangnguyen** [comment]
> @vitokhangnguyen Can you see the image above? I am in your branch. If it is old version of code then your branch has an old version

I do see that. A very strange behavior because it is not the case on my side. Will continue looking into it.

**Comment by vitokhangnguyen** [comment]
@Haider8 
Hi, I did not realize that the project is not using requirements.txt to save dependencies anymore. Instead, they are in setup.py. I am just curious but may I know why this change happened?
I added `readchar` to dependencies in setup.py.

@Shanmugapriya03 
As for the behaviour above, I think there might be one possibility that your code looks like it is in an older version. You might have done `pip install .` before switching to my branch making the executable built from the master branch obsolete. The command needs to be executed every time there is a change in code to build a new executable.
Can you please try this procedure one more time? I know you put a lot of effort already.

Checkout to my branch if you are not already there:
```
git checkout issue-11
```
Update your clone to be the same as mine:
```
git pull master issue-11
```
Setup/rebuild the application (it is important that you do this  after checking out to `issue-11`)
```
pip install .
```
Then you can test my work. Please give me some feedback after this if you can.

**Comment by Shanmugapriya03** [comment]
@vitokhangnguyen Just to avoid confusions I deleted the folder from my system and cloned it again using this command
`git clone --single-branch -branch issue-11 https://github.com/vitokhangnguyen/tmessage.git`
Then did `pip install .`

Your fix kind of works but it gives 2 new major issues
1. The cursor is always in the middle and the content is also not clearly visible. Ideally, it should be at the beginning of the new line
Here is an image for a clear understanding of the issue
Screenshot 2019-10-20 at 11 38 22 AM
Screenshot 2019-10-20 at 11 42 25 AM
Screenshot 2019-10-20 at 11 41 58 AM
after sending the message also it is not displayed from the beginning of the line

2. `ctrl+c` option is not working to end the chat. The terminal is getting hanged

@Haider8  Can you try it in your Ubuntu and let me know if you face similar issue... I tested it in my mac

**Comment by vitokhangnguyen** [comment]
@Shanmugapriya03 Thanks for testing out,

I have an idea on how to fix the cursor problem. It may be the different interpretation of a newline between Windows and Unix-like systems.
On my side, the Ctrl + C works fine. I will look into this and add some checks.

**Comment by vitokhangnguyen** [comment]
@Shanmugapriya03 I just made some small changes. Please pull from my repo/branch and build again before testing it out when you have time.
```
git pull origin issue-11
pip install .
```

**Comment by Haider8** [comment]
@Shanmugapriya03 Please test it. The issue of cursor shifting ahead is still present for me.

**Comment by Shanmugapriya03** [comment]
@Haider8 This issue still exist for me too @vitokhangnguyen 
Screenshot 2019-10-21 at 12 47 42 PM
Screenshot 2019-10-21 at 12 47 21 PM
Screenshot 2019-10-21 at 12 47 00 PM

**Comment by vitokhangnguyen** [comment]
I will find a Mac system and do some testing/fixing on that. Thank you for your feedbacks.

**Comment by vitokhangnguyen** [comment]
Hi @Haider8 @Shanmugapriya03,
I managed to reproduce the problem you have on a VMWare Ubuntu system and made some changes to fix it. I think the result is in the right direction now, although I can use some improvements.

**Comment by Shanmugapriya03** [comment]
@vitokhangnguyen Sorry for the delay in review. Your fix worked but introduced a new issue attaching a screenshot of the issue


The incoming message is filling the extra space left with the unsend message cc: @Haider8

**Comment by vitokhangnguyen** [comment]
Hi @Shanmugapriya03,

Thank you for pointing that out, I believe that has been fixed/ As I said, the current input module could use a lot of improvement.

**Comment by Shanmugapriya03** [comment]
@vitokhangnguyen Works perfectly Fine! @Haider8  I am Approving this PR please do merge it

**Review by Shanmugapriya03 — APPROVED** [review]

**Pull request merged**
