### PR TITLE
Publish package on Pypi

### PR DESCRIPTION
**Pull request by Haider8**

### CODE REVIEW

**Comment by Haider8** [comment]
@Shanmugapriya03 Why the tests are failing here?

**Comment by Shanmugapriya03** [comment]
I didn't change anything in ` file tmessage/__init__.py:` Let me check the `setup.py` maybe pep8 and pylint format are conflicting

**Comment by Shanmugapriya03** [comment]
@Haider8  Were you able to figure this one out?

**Comment by Haider8** [comment]
@Shanmugapriya03 Don't you think that we should have some limit on pylint score (maybe 9?). It will be very difficult to have the perfect score.

**Comment by Haider8** [comment]
@pep8speaks suggest diff

**Comment by Shanmugapriya03** [comment]
#42 @Haider8

**Pull request merged**
