### PR TITLE
add functionality to run tmessage without python command

### PR DESCRIPTION
**Pull request by pangeran-bottor**
The reference for this is https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#

Basically I create `tmessage` as a module and add `cli.py` as a copy from `msg.py` (just in case future development would be different between cli tool and module level).

I also add the instruction to run this as `tmessage <args>` on `README.md`.

Tested on my local machine only using `USERNAME` argument so if you have your own broker, I would be grateful if you could test this.

### CODE REVIEW

**Comment by Haider8** [comment]
Great work @pangeran-bottor :100: I have tested it with my own broker using this commmand `tmessage --user Haider8 --server localhost --port 1883` and it's working perfectly fine. I think we should focus on making tmessage just a `cli tool`. What are your thoughts on this?

If you agree on this then we can change the README so as to just show the instructions for using it as a cli tool and delete the `msg.py` file. 

Again, thank you for this wonderful work!

**Comment by pangeran-bottor** [comment]
Thanks for the feedback @Haider8.

I'm totally agree with that.

**Comment by Haider8** [comment]
@pangeran-bottor Just do those changes and I think we can then merge this PR

**Comment by pangeran-bottor** [comment]
Hi @Haider8, please review these changes.

**Comment by Haider8** [comment]
@pangeran-bottor PR looks good to go :+1: 
fixes #13

**Comment by Haider8** [comment]
@pangeran-bottor You can open some new issues or work on existing issues if you want.

**Pull request merged**
