### PR TITLE
feat: Set port from "--port"  arg in execution script

### LINKED ISSUE #7: feat(main): add PORT flag
# 🚀 feature request

### Relevant Package
main.py

### Description
Add PORT flag to the initial script execution

### Describe the solution you'd like
In `main.py` add initialise `BROKER_PORT` flag which can later be used after the arguments have been parsed. Something along the lines of 

> BROKER_PORT = args.port or 1883.

### PR DESCRIPTION
**Pull request by roshnet**
This enables the user to specify the port number while
executing the main script. If none specified, the default
port is taken to be 1883.
Fixes #7

### CODE REVIEW

**Comment by Haider8** [comment]
@roshnet Great work Roshan. Can you please reflect these changes in the README file also

**Comment by roshnet** [comment]
@Haider8 updating the PR, standby for merge.

**Comment by Haider8** [comment]
@roshnet Are we finalizing this PR?

**Comment by roshnet** [comment]
I got pinned down, on it ASAP.

**Pull request merged**
